In [22]:
from FlagTools import FlagTools as ft
import numpy as np

Setting up the required variables for the Jupyter notebook.

In [23]:
dim = 4

fMinus = np.identity(dim)   # standard ascending flag
fPlus = np.flip(fMinus,0)   # standard descending flag

componentMatrices = ft.generateComponentMatrices(dim)
#print("The number of component matrices constructed is " + str(len(componentMatrices)))

EMatrices = ft.generateEMatrices(dim)

Experiment #1: Testing which component matrices admit a representative flag F such that the signs of the triple ratios of (F-,F,F+) agree with
the signs of the triple ratios of (F-, \iota F, F+). By Dey's result, we know that no component of the double Schubert cell C(F-,F+) is
preserved by iota. However, there may be multiple components of C(F-,F+) which lie in the same component of the configuration space Conf_3 of (ordered) triples of
flags. In other words, two flag triples in different components of C(F-,F+) may still have the same triple ratio signs, so checking the signs of the triple ratios
of the triples (F-,F,F+) and (F-,\iota F,F+) will not lead to a complete answer. Despite this, there will likely be many cases in which the signs are different.

For further experimentation, we also keep track of which component matrices admit representative flags F such that (F-,F,F+) and (F-,\iota F,F+) have triple ratios which agree in sign.

In [24]:
""" Experiment #1 """

nonIotaPreservedComponentMatrices = []
nonIotaCount = 0
iotaPreservedComponentMatrices = []
for componentMatrix in componentMatrices:
    f = ft.getFlagRepresentative(componentMatrix, fPlus, dim, EMatrices)
    iota_f = np.matmul(np.matmul(fPlus, np.linalg.inv(f)), fPlus)
    tripleRatios = ft.tripleRatios([fMinus, f, fPlus])
    iotaTripleRatios = ft.tripleRatios([fMinus, iota_f, fPlus])
    nonIotaPreserved = False

    for index in range(0,len(tripleRatios)):
        if tripleRatios[index]*iotaTripleRatios[index] < 0:
            nonIotaPreserved = True

    if nonIotaPreserved:
        nonIotaCount += 1
        nonIotaPreservedComponentMatrices.append(componentMatrix)
    else:
        iotaPreservedComponentMatrices.append(componentMatrix)

print("The number of component matrices detected by this experiment to represent components which are not iota preserved is " + str(nonIotaCount))

The number of component matrices detected by this experiment to represent components which are not iota preserved is 32


Experiment #1 continued: Here we list the representative flag F of any component matrix for which (F-,F,F+) and (F-,\iota F,F+) have triples ratios which agree in sign.

In [25]:
for c in iotaPreservedComponentMatrices:
    print(str(c))
    F = ft.getFlagRepresentative(c,fPlus,dim,EMatrices)
    print(F)
    tripleRatios = ft.tripleRatiosPairedWithTriples((fMinus, F, fPlus))
    print(tripleRatios)
    print("--------------")

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 3. 3. 1.]
 [1. 2. 1. 0.]
 [1. 1. 0. 0.]
 [1. 0. 0. 0.]]
[(np.float64(1.0), (1, 1, 2)), (np.float64(1.0), (1, 2, 1)), (np.float64(1.0), (2, 1, 1))]
--------------
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[-1.  1.  3.  1.]
 [-1.  0.  1.  0.]
 [ 1.  1.  0.  0.]
 [ 1.  0.  0.  0.]]
[(np.float64(1.0), (1, 1, 2)), (np.float64(0.9999999999999998), (1, 2, 1)), (np.float64(-1.0), (2, 1, 1))]
--------------
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 2. 1. 0.]
 [1. 1. 0. 0.]
 [1. 0. 0. 0.]]
[(np.float64(-1.0), (1, 1, 2)), (np.float64(-1.0), (1, 2, 1)), (np.float64(1.0), (2, 1, 1))]
--------------
[[0. 0. 0.]
 [0. 1. 1.]
 [0. 0. 0.]]
[[-1. -1.  1.  1.]
 [-1.  0.  1.  0.]
 [ 1.  1.  0.  0.]
 [ 1.  0.  0.  0.]]
[(np.float64(-1.0), (1, 1, 2)), (np.float64(-1.0), (1, 2, 1)), (np.float64(-1.0), (2, 1, 1))]
--------------
[[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[-1.  3.  3.  1.]
 [-1.  2.  1.  0.]
 [-1.  1.  0.  0.]
 [ 1.  0.  0.  0.]]
[(np.float64(1.0)

Experiment #2: Testing which component matrices admit a representative flag F such that (F-,F,F+) and the cyclic permutation (F,F+,F-) have triple ratios which
agree in sign.

In [26]:
cyclicComponentMatrices = []
cCMCount = 0

for componentMatrix in componentMatrices:
    f = ft.getFlagRepresentative(componentMatrix,fPlus, dim, EMatrices)
    tripleRatios = ft.tripleRatios([fMinus, f, fPlus])
    cycledTripleRatios = ft.tripleRatios([f, fPlus, fMinus])
    cyclic = True
    for index in range(0,len(tripleRatios)):
        if tripleRatios[index]*cycledTripleRatios[index] < 0:
            cyclic = False
    
    if cyclic:
        cyclicComponentMatrices.append(componentMatrix)
        cCMCount += 1

In [29]:
print("The number of components admiting a flag such that cyclic permutations agree in their triple ratio is " + str(cCMCount))

The number of components admiting a flag such that cyclic permutations agree in their triple ratio is 16


Experiment #3: Testing which component matrices admit a representative flag F such that (F-,F,F+) and (F+,F,F-) have triple ratios that agree in sign. We remark here
that the point is to detect for which components may possibly (but not necessarily) admit limit sets which allow the triples (F-,F,F+) and (F+,F,F-) to be interchanged within the limit set. Such a limit set would need to be larger than a curve in the sense that it would need to contain a tripod.

In [9]:
reversableComponentMatrices = []
rCMCount = 0

for componentMatrix in componentMatrices:
    f = ft.getFlagRepresentative(componentMatrix,fPlus, dim, EMatrices)
    tripleRatios = ft.tripleRatios([fMinus, f, fPlus])
    reversedTripleRatios = ft.tripleRatios([fPlus, f, fMinus])

    reversable = True

    for index in range(0,len(tripleRatios)):
        if tripleRatios[index]*reversedTripleRatios[index] < 0:
            reversable = False
    
    if reversable:
        reversableComponentMatrices.append(componentMatrix)
        rCMCount += 1

In [30]:
print("The number of components admitting a flag F such that (F-,F,F+) and (F+,F,F-) agree in triple ratio is "+str(rCMCount))

The number of components admitting a flag F such that (F-,F,F+) and (F+,F,F-) agree in triple ratio is 32


Experiment #4: We now count the number of elements in the intersection of the lists of component matrices we have constructed in Experiments #2 and #3. In other words, we check for the
component matrices which admit a representative flag F such that both
 - (F-,F,F+) and (F,F+,F-) lie in the same component of Conf_3, and
 - (F-,F,F+) and (F+,F,F-) lie in the same component of Conf_3.

In [32]:
combinedListOfComponentMatrices = []
for componentMatrix in reversableComponentMatrices:
    for otherComponentMatrix in cyclicComponentMatrices:
        if np.array_equal(componentMatrix, otherComponentMatrix):
            combinedListOfComponentMatrices.append(componentMatrix)
print(len(combinedListOfComponentMatrices))

16


Experiment #5: We now count the number of elements in the intersection of the lists of component matrices we have constructed in Experiments #1 and #2. In other words, we count the component
matrices which admit a representative flag F such that both
 - (F-,F,F+) and (F-, \iota F, F+) lie in the same component of Conf_3, and
 - (F-,F,F+) and (F+,F,F-) lie in the same component of Conf_3.

In [34]:
combinedListOfComponentMatricesTwo = []
for componentMatrix in iotaPreservedComponentMatrices:
    for otherComponentMatrix in cyclicComponentMatrices:
        if np.array_equal(componentMatrix, otherComponentMatrix):
            combinedListOfComponentMatricesTwo.append(componentMatrix)
print(len(combinedListOfComponentMatricesTwo))

16
